name:  building .net application
on: 
  push:

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      
      - name: print before build
        run: ls -LR HelloWorldApp/bin
      
      - name: checkout from source
        uses: actions/checkout@v3

      - name: build app
        run: dotnet build

      - name: print before build
        run: ls -LR HelloWorldApp/bin
    